Update animals table
XsidX/vet-clinic-db pull request #2
Opened 2022-09-13 18:22 UTC by XsidX

> For this PR, I:
  - [use serial data_type for primary key](https://github.com/XsidX/vet-clinic-db/commit/f2d1de3c00fedef4ffe062a5aaa1b8a261dea376)
  - [add species column](https://github.com/XsidX/vet-clinic-db/commit/5a683c3bd836fffc6aa5d1ad82c8abbbdab6a330)
  - [insert 7 more records](https://github.com/XsidX/vet-clinic-db/commit/25e88d09e40461480a266b3fdea97267cc9fd506)
  - [add some more queries & transactions](https://github.com/XsidX/vet-clinic-db/commit/fd3e05b0cfc18cd6ff3962923e2633c6da392fd6)
  - [add screenshots for transactions and new queries](https://github.com/XsidX/vet-clinic-db/commit/b598f3bfde075ef56ff30d4a63d50732087337b5)

> **update species column in a transaction**
![update-species](https://user-images.githubusercontent.com/41898352/189978228-bdb78697-3367-41dd-84d9-0d628a13a97c.PNG)

> **delete all records using a transaction**
![delete-all-records](https://user-images.githubusercontent.com/41898352/189978548-4ccf0556-9b91-4fa5-a00f-45bd519824b0.PNG)

 > **roll back records deletion**
![delete-all-records-after-rollback](https://user-images.githubusercontent.com/41898352/189978648-f9e7aa44-0182-4500-9e14-1fc4fb2732ed.PNG)

> **delete-where-born-after-jan1st2022 using a transaction**
![delete-where-born-after-jan1st2022](https://user-images.githubusercontent.com/41898352/189978927-27b2f742-5530-4a56-b97d-38c82f464c8f.PNG)

> **add savepoint _save_1_**
![add-save-point-1](https://user-images.githubusercontent.com/41898352/189979138-895758f5-dca5-4e2c-b031-86bca18c9889.PNG)

> **update weight to -ve weight**
![update-weight-to-negative-weight](https://user-images.githubusercontent.com/41898352/189979300-c408ecf6-b956-4e64-9a1d-56444d90378b.PNG)

> **rollback to savepoint _save_1_**
![rollback-to-savepoint-1](https://user-images.githubusercontent.com/41898352/189979469-0df94db2-c591-4358-a94c-b696e998dbeb.PNG)

> **output from rollback to savepoint _save_1_** 
![rollback-to-savepoint-output](https://user-images.githubusercontent.com/41898352/189979622-208101a4-34af-4e94-b2ff-ac6fedeaf22d.PNG)

> **update weight where -ve**
![update-weight-where-negative](https://user-images.githubusercontent.com/41898352/189979850-2140ee96-6e06-421e-a46d-a1b20b7ee735.PNG)

> **commit transactions**
![commit-transactions](https://user-images.githubusercontent.com/41898352/189980068-5e659303-fc1e-404f-8dc5-4e4a2bdec00b.PNG)

> **final output after commit**
![output-after-commit](https://user-images.githubusercontent.com/41898352/189980150-797f0978-c148-45ba-936d-008a18cf7476.PNG)

2022-09-13 18:47 UTC, tufoinnkuo10 requested changes
Hi @XsidX 

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ Documented your work professionally
✔️ screenshots

Required Changes ♻️
Check the comments under the review
Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-09-13 18:47 UTC, tufoinnkuo10 commented on queries.sql
> +SELECT species, AVG(escape_attempts) AS avg_escape_attempts FROM animals GROUP BY species
- [ ] Great job. You did a wonderful job with the queries and screenshot. Please add comments of the query questions you are answering here to ease the viewer know what you did and help you as well in the future.

2022-09-13 19:04 UTC, XsidX commented on queries.sql
> +SELECT species, AVG(escape_attempts) AS avg_escape_attempts FROM animals GROUP BY species
@tufoinnkuo10 
thanks for the suggestion 👍🏽, 
but this is not a strict requirement to warrant **required changes**

2022-09-14 08:23 UTC, brytebee approved these changes
Hi, @XsidX👋,

##

### Highlights💡
- Good commit message.✔️ 
- Good PR Summary.✔️
- Great schema design and queries.✔️
- App functions as it should.✔️

##

# STATUS: APPROVED 🕺🥳 

Congratulations🍾🥳!! Your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![](https://media.giphy.com/media/vmtxnxveVUodG/giphy.gif)

##

###  **Optional Suggestions:**
- N/A

##

Good luck! 🎉 

------

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-14 08:38 UTC, merged